# Generated by Django 5.2.6 on 2025-09-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_category_options_alter_subtask_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category',
        ),
        migrations.RemoveConstraint(
            model_name='subtask',
            name='unique_subtask',
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_task',
        ),
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название подзадачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100, unique=True, unique_for_date='created_at', verbose_name='Название задачи'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_category_name'),
        ),
        migrations.AddConstraint(
            model_name='subtask',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_subtask_title'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_task_title'),
        ),
    ]
